version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_DB: nestjs_advansed
      POSTGRES_USER: nestjs_advansed
      POSTGRES_PASSWORD: Arm20032003
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
